name: Ad-creatives

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  BUILD_NUMBER: 1
  BUILD_VERSION: 1.0.0
  PYTHON_VERSION: 3.12.5
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build Project
      run: |
        # Command to build the project (for example, creating a static website)
        # If this is a static web app, adjust the command according to your build process
        python your_build_script.py

    - name: Upload Build Artifact
      uses: actions/upload-pages-artifact@v3
      with:
        name: web-build-artifact  # This is the name of the artifact being created
        path: ./build  # Path to the directory where your build output is stored

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
